pipeline:
  deploy:
    image: ktruckenmiller/ansible:dind
    environment:
      - AWS_DEFAULT_REGION=us-west-2
    commands:
      - ansible-playbook -i ansible_connection=localhost deploy.yml
    when:
      event: [ push ]
      branch: [ master ]
